image:
  repository: "ghcr.io/harubaru/s3manager/s3manager"
  tag: "5b7506c"
  pullPolicy: IfNotPresent

nodeSelector:
  region: LAS1

ingress:
  enabled: true

s3:
  accessKey: ""
  secretKey: ""
  endpoint: ""

app:
  username: ""
  password: ""
  sessionKey: ""
