{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-s3manager
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: {{ template "s3manager.ingress_host" . }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-s3manager
          servicePort: 80
        path: /
        pathType: ImplementationSpecific
  tls:
    - hosts:
      - {{ template "s3manager.ingress_host" . }}
      secretName: {{ .Release.Name }}-s3manager-tls
{{- end }}
