apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-s3manager-secrets
type: Opaque
data:
  s3-access-key: {{ .Values.s3.accessKey | b64enc }}
  s3-secret-key: {{ .Values.s3.secretKey | b64enc }}
  s3-endpoint: {{ .Values.s3.endpoint | b64enc }}
  app-username: {{ .Values.app.username | b64enc }}
  app-password: {{ .Values.app.password | b64enc }}
  app-session-key: {{ .Values.app.sessionKey| b64enc }}
